
import { InteriorStyle, CurtainColor, CurtainLayer } from './types';

export const CURTAIN_COLORS: CurtainColor[] = [
  { id: 'white', name: 'White (ขาว)', hex: '#FFFFFF', prompt: 'clean white', class: 'bg-white border-slate-200' },
  { id: 'cream', name: 'Cream (ครีม)', hex: '#FDFDD0', prompt: 'soft cream color', class: 'bg-[#FDFDD0] border-slate-200' },
  { id: 'beige', name: 'Beige (เบจ)', hex: '#F5F5DC', prompt: 'warm beige', class: 'bg-[#E8DFC5] border-slate-200' },
  { id: 'light-grey', name: 'Light Grey (เทาอ่อน)', hex: '#D3D3D3', prompt: 'light grey', class: 'bg-slate-300 border-slate-400' },
  { id: 'dark-grey', name: 'Dark Grey (เทาเข้ม)', hex: '#4A4A4A', prompt: 'dark charcoal grey', class: 'bg-slate-700 border-slate-600' },
  { id: 'black', name: 'Black (ดำ)', hex: '#1a1a1a', prompt: 'black', class: 'bg-black border-slate-600' },
  { id: 'navy', name: 'Navy (น้ำเงิน)', hex: '#000080', prompt: 'deep navy blue', class: 'bg-blue-900 border-blue-800' },
  { id: 'light-blue', name: 'Light Blue (ฟ้า)', hex: '#ADD8E6', prompt: 'soft light blue', class: 'bg-sky-200 border-sky-300' },
  { id: 'brown', name: 'Brown (น้ำตาล)', hex: '#8B4513', prompt: 'earthy brown', class: 'bg-[#8B4513] border-[#5D2E0C]' },
  { id: 'gold', name: 'Gold (ทอง)', hex: '#D4AF37', prompt: 'luxury gold color', class: 'bg-[#D4AF37] border-[#B8860B]' },
  { id: 'green', name: 'Green (เขียว)', hex: '#556B2F', prompt: 'natural sage green', class: 'bg-[#556B2F] border-[#3A4A1F]' },
  { id: 'pink', name: 'Pink (ชมพู)', hex: '#FFC0CB', prompt: 'soft pastel pink', class: 'bg-pink-200 border-pink-300' },
];

export const CURTAIN_LAYERS: CurtainLayer[] = [
  { 
    id: '1-layer', 
    name: '1 ชั้น (Single Layer)', 
    description: 'ผ้าทึบหรือผ้าโปร่งเพียงชั้นเดียว',
    prompt: 'single layer' 
  },
  { 
    id: '2-layer', 
    name: '2 ชั้น (Double Layer)', 
    description: 'ผ้าทึบพร้อมผ้าโปร่งกรองแสงด้านใน',
    prompt: 'double layer with inner white sheer curtain and outer blackout curtain' 
  },
];

export const INTERIOR_STYLES: InteriorStyle[] = [
  {
    id: 'minimalist',
    name: 'Minimalist & Muji',
    icon: '🌿',
    description: 'เรียบง่าย โปร่งโล่ง สบายตา โทนสีขาว ครีม ไม้',
    colors: 'bg-stone-50 text-stone-800 border-stone-200',
    curtains: [
      {
        id: 's-curve-mini',
        name: 'ม่านลอน (S-Curve)',
        description: 'ลอนสวย ทันสมัย ดูโปร่งสบาย',
        promptModifier: 'S-Curve curtains, wave fold drapery, soft fabric, minimalist muji style interior',
      },
      {
        id: 'pleated-mini',
        name: 'ม่านจีบ (Pleated)',
        description: 'จีบเล็ก เรียบง่าย ดูสะอาดตา',
        promptModifier: 'Simple pleated curtains, clean straight lines, minimalist muji style',
      },
      {
        id: 'eyelet-mini',
        name: 'ม่านตาไก่ (Eyelet)',
        description: 'ลอนสวยธรรมชาติ ติดตั้งง่าย ดูทันสมัย',
        promptModifier: 'Eyelet curtains with metal rings, soft wave fold, minimalist muji style',
      },
      {
        id: 'bamboo-mini',
        name: 'ม่านไม้ไผ่ (Bamboo Blinds)',
        description: 'ธรรมชาติ สไตล์ญี่ปุ่น/Zen ให้ความรู้สึกสงบ',
        promptModifier: 'Bamboo roll-up blinds, natural woven wood texture, japanese zen minimalist style, soft filtered light',
      },
      {
        id: 'roller-mini',
        name: 'ม่านม้วน (Roller Blinds)',
        description: 'เรียบง่าย ประหยัดพื้นที่ ทันสมัย',
        promptModifier: 'Roller shades, flat clean fabric window covering, minimalist interior',
      },
      {
        id: 'sheer-mini',
        name: 'เฉพาะผ้าโปร่ง (Sheer Only)',
        description: 'เน้นความโปร่งแสง สบายตา ให้แสงธรรมชาติเข้า',
        promptModifier: 'Sheer curtains only, translucent white fabric, soft natural light, minimalist style',
      },
      {
        id: 'roman-mini',
        name: 'ม่านพับ (Roman)',
        description: 'เรียบง่าย ประหยัดพื้นที่ สไตล์มูจิ',
        promptModifier: 'Fabric Roman blinds, flat fold shades, clean minimalist look',
      },
      {
        id: 'wooden-mini',
        name: 'มู่ลี่ไม้ (Wooden Blinds)',
        description: 'ไม้ธรรมชาติ ให้ความรู้สึกอบอุ่น',
        promptModifier: 'Wooden venetian blinds, horizontal slats, warm minimalist style',
      },
      {
        id: 'vertical-mini',
        name: 'ม่านปรับแสง (Vertical Blinds)',
        description: 'เส้นสายแนวตั้ง เรียบง่าย สะอาดตา',
        promptModifier: 'Vertical blinds, fabric slats, clean lines, minimalist interior',
      },
    ],
  },
  {
    id: 'scandinavian',
    name: 'Scandinavian',
    icon: '❄️',
    description: 'อบอุ่น เน้นแสงธรรมชาติ โทนขาว-เทา และงานไม้',
    colors: 'bg-slate-50 text-slate-800 border-slate-200',
    curtains: [
      {
        id: 's-curve-scan',
        name: 'ม่านลอน (S-Curve)',
        description: 'ผ้าเนื้อลินินหรือฝ้าย ทิ้งตัวเป็นธรรมชาติ',
        promptModifier: 'S-Curve curtains, linen texture, soft drapery, bright scandinavian interior',
      },
      {
        id: 'pleated-scan',
        name: 'ม่านจีบ (Pleated)',
        description: 'เรียบง่าย เข้ากับเฟอร์นิเจอร์สแกนดิเนเวียน',
        promptModifier: 'Simple pleated curtains, cotton fabric, clean scandinavian style',
      },
      {
        id: 'eyelet-scan',
        name: 'ม่านตาไก่ (Eyelet)',
        description: 'โชว์รางม่าน ให้ความรู้สึกอบอุ่น เป็นกันเอง',
        promptModifier: 'Eyelet curtains, natural linen fabric, wood or metal rod, scandinavian style',
      },
      {
        id: 'roller-scan',
        name: 'ม่านม้วน (Roller Blinds)',
        description: 'สีอ่อน สะอาดตา กรองแสงนุ่มนวล',
        promptModifier: 'White or light grey roller shades, flat fabric window blind, clean scandinavian style',
      },
      {
        id: 'sheer-scan',
        name: 'เฉพาะผ้าโปร่ง (Sheer Only)',
        description: 'เปิดรับแสงธรรมชาติ ให้ห้องดูสว่าง',
        promptModifier: 'Sheer curtains only, light airy fabric, scandinavian living room',
      },
      {
        id: 'roman-scan',
        name: 'ม่านพับ (Roman)',
        description: 'สะอาดตา ประหยัดพื้นที่',
        promptModifier: 'Fabric Roman blinds, clean design, scandinavian home',
      },
      {
        id: 'wooden-scan',
        name: 'มู่ลี่ไม้ (Wooden Blinds)',
        description: 'ไม้สีอ่อน (Light Oak) เข้ากับพื้นห้อง',
        promptModifier: 'Light wood venetian blinds, birch or oak wood, scandinavian style',
      },
      {
        id: 'vertical-scan',
        name: 'ม่านปรับแสง (Vertical Blinds)',
        description: 'ทันสมัย เรียบง่าย ดูแลรักษาง่าย',
        promptModifier: 'Vertical blinds, white or light grey, scandinavian interior',
      },
    ],
  },
  {
    id: 'luxury',
    name: 'Modern Luxury',
    icon: '💎',
    description: 'หรูหรา ทันสมัย วัสดุเงาวาว หินอ่อน สีทอง/เงิน',
    colors: 'bg-slate-900 text-slate-50 border-slate-700',
    curtains: [
      {
        id: 'louis-lux',
        name: 'ม่านหลุยส์ (Louis Curtain)',
        description: 'ตกแต่งหรูหรา มีลูกเล่นหัวม่าน ชายครุย',
        promptModifier: 'Luxury Louis style curtains, ornamental swags and tails, valance, elegant classical drapery, premium fabric',
      },
      {
        id: 's-curve-lux',
        name: 'ม่านลอน (S-Curve)',
        description: 'ลอนลึก ผ้าทิ้งตัวสวย เพิ่มความโอ่อ่า',
        promptModifier: 'Luxury velvet S-Curve curtains, shiny texture, floor to ceiling, modern luxury style',
      },
      {
        id: 'pleated-lux',
        name: 'ม่านจีบ (Pleated)',
        description: 'จีบสวยงาม คลาสสิก หรูหรา',
        promptModifier: 'Premium pinch pleat curtains, elegant drapery, luxury interior',
      },
      {
        id: 'eyelet-lux',
        name: 'ม่านตาไก่ (Eyelet)',
        description: 'ห่วงตาไก่สีทองหรือเงิน เพิ่มความหรูหรา',
        promptModifier: 'Luxury eyelet curtains, gold or silver rings, premium velvet or silk fabric, modern luxury interior',
      },
      {
        id: 'roller-lux',
        name: 'ม่านม้วน (Roller Blinds)',
        description: 'ม่านม้วนไฟฟ้า หรือผ้า Blackout ผิวเรียบหรู',
        promptModifier: 'Premium roller shades, motorized, smooth high-end fabric, luxury interior',
      },
      {
        id: 'roman-lux',
        name: 'ม่านพับ (Roman)',
        description: 'พับลอนใหญ่ ตกแต่งขอบเพิ่มความหรู',
        promptModifier: 'Luxury Roman blinds, high-end fabric, elegant folds, modern luxury bedroom',
      },
      {
        id: 'wooden-lux',
        name: 'มู่ลี่ไม้ (Wooden Blinds)',
        description: 'มู่ลี่ไม้เกรดพรีเมียม สีเข้มหรือสีเงา',
        promptModifier: 'Premium wooden venetian blinds, polished finish, luxury interior',
      },
      {
        id: 'vertical-lux',
        name: 'ม่านปรับแสง (Vertical Blinds)',
        description: 'ม่านปรับแสงเนื้อผ้าหรูหรา กัน UV',
        promptModifier: 'High-end vertical blinds, premium fabric slats, modern luxury style',
      },
      {
        id: 'sheer-lux',
        name: 'เฉพาะผ้าโปร่ง (Sheer Only)',
        description: 'ผ้าโปร่งลายลูกไม้หรือเนื้อทราย เพิ่มความหรูหรา',
        promptModifier: 'Sheer curtains only, premium lace or textured sheer fabric, elegant luxury style',
      },
    ],
  },
  {
    id: 'modern-classic',
    name: 'Modern Classic',
    icon: '🏛️',
    description: 'ผสานความคลาสสิกเข้ากับความทันสมัย สง่างาม',
    colors: 'bg-indigo-50 text-indigo-900 border-indigo-200',
    curtains: [
      {
        id: 'louis-modclass',
        name: 'ม่านหลุยส์ (Louis Curtain)',
        description: 'ลดทอนความอลังการลง ให้ดูทันสมัยขึ้น',
        promptModifier: 'Modern classic Louis style curtains, refined swags, elegant drapery, sophisticated interior',
      },
      {
        id: 'pleated-modclass',
        name: 'ม่านจีบ (Pleated)',
        description: 'คลาสสิกเหนือกาลเวลา เข้ากับคิ้วบัวผนัง',
        promptModifier: 'Classic pinch pleat curtains, rich fabric, modern classic interior with wall moldings',
      },
      {
        id: 'eyelet-modclass',
        name: 'ม่านตาไก่ (Eyelet)',
        description: 'ผสมผสานความคลาสสิกกับความทันสมัย',
        promptModifier: 'Modern classic eyelet curtains, elegant drapery, decorative rod, sophisticated style',
      },
      {
        id: 's-curve-modclass',
        name: 'ม่านลอน (S-Curve)',
        description: 'เรียบหรู ดูแพง ผ้าเนื้อดี',
        promptModifier: 'Elegant S-Curve curtains, high quality fabric, modern classic style',
      },
      {
        id: 'roller-modclass',
        name: 'ม่านม้วน (Roller Blinds)',
        description: 'เรียบง่าย ตัดกับความคลาสสิกอย่างลงตัว',
        promptModifier: 'Simple roller shades, clean flat design, modern classic interior',
      },
      {
        id: 'roman-modclass',
        name: 'ม่านพับ (Roman)',
        description: 'มีลูกเล่นกุ๊นขอบ หรือใช้ผ้าลายคลาสสิก',
        promptModifier: 'Roman blinds with border trim, classic fabric pattern, modern classic home',
      },
      {
        id: 'wooden-modclass',
        name: 'มู่ลี่ไม้ (Wooden Blinds)',
        description: 'ไม้สีวอลนัท หรือสีขาวคลาสสิก',
        promptModifier: 'Classic wooden venetian blinds, polished wood, modern classic style',
      },
      {
        id: 'sheer-modclass',
        name: 'เฉพาะผ้าโปร่ง (Sheer Only)',
        description: 'เพิ่มความอ่อนโยนให้กับห้อง',
        promptModifier: 'Sheer curtains only, elegant soft fabric, modern classic style',
      },
    ],
  },
  {
    id: 'loft',
    name: 'Loft / Industrial',
    icon: '🧱',
    description: 'ดิบ เท่ โชว์โครงสร้าง ปูนเปลือย อิฐ',
    colors: 'bg-zinc-800 text-zinc-100 border-zinc-600',
    curtains: [
      {
        id: 'pleated-loft',
        name: 'ม่านจีบ (Pleated)',
        description: 'ม่านจีบรางโชว์ เข้ากับสไตล์ลอฟท์',
        promptModifier: 'Pleated curtains with exposed metal track, industrial loft style',
      },
      {
        id: 'eyelet-loft',
        name: 'ม่านตาไก่ (Eyelet)',
        description: 'โชว์รางเหล็กและห่วงตาไก่ เข้ากับสไตล์ลอฟท์',
        promptModifier: 'Industrial eyelet curtains, black metal rod, heavy cotton or canvas fabric, loft style',
      },
      {
        id: 'roller-loft',
        name: 'ม่านม้วน (Roller Blinds)',
        description: 'ผ้า Sunscreen สีเข้ม กรองแสงแต่ยังเห็นวิว',
        promptModifier: 'Dark grey or black roller shades, sunscreen fabric, industrial loft style',
      },
      {
        id: 'wooden-loft',
        name: 'มู่ลี่ไม้ (Wooden Blinds)',
        description: 'ไม้สีเข้ม หรือดำ เท่ ดิบ เข้ากับปูนเปลือย',
        promptModifier: 'Dark wooden venetian blinds, industrial loft style, raw aesthetic',
      },
      {
        id: 'roman-loft',
        name: 'ม่านพับ (Roman)',
        description: 'เนื้อผ้าหยาบหรือยีนส์ เท่ไม่เหมือนใคร',
        promptModifier: 'Roman blinds, tough fabric texture, industrial style',
      },
      {
        id: 'vertical-loft',
        name: 'ม่านปรับแสง (Vertical Blinds)',
        description: 'คุมแสงได้ดี เข้ากับกระจกบานใหญ่',
        promptModifier: 'Vertical blinds, grey or black fabric, loft interior',
      },
      {
        id: 'sheer-loft',
        name: 'เฉพาะผ้าโปร่ง (Sheer Only)',
        description: 'ผ้าโปร่งสีเทาหรือขาวบาง ให้ความเท่',
        promptModifier: 'Sheer curtains only, grey or white sheer fabric, industrial loft style',
      },
    ],
  },
  {
    id: 'tropical',
    name: 'Tropical / Resort',
    icon: '🌴',
    description: 'ผ่อนคลาย สไตล์รีสอร์ท ใกล้ชิดธรรมชาติ',
    colors: 'bg-emerald-50 text-emerald-900 border-emerald-200',
    curtains: [
      {
        id: 'wooden-trop',
        name: 'มู่ลี่ไม้ (Wooden Blinds)',
        description: 'ไม้ธรรมชาติ สำคัญมากสำหรับสไตล์นี้',
        promptModifier: 'Natural wooden venetian blinds, bamboo texture, tropical resort style, indoor plants',
      },
      {
        id: 'bamboo-trop',
        name: 'ม่านไม้ไผ่ (Bamboo Blinds)',
        description: 'ลายสานธรรมชาติ เข้ากับสไตล์รีสอร์ท',
        promptModifier: 'Bamboo blinds, natural woven wood, tropical resort style, warm atmosphere',
      },
      {
        id: 'roller-trop',
        name: 'ม่านม้วน (Roller Blinds)',
        description: 'เน้นโทนสีธรรมชาติ หรือลายสาน',
        promptModifier: 'Textured roller shades, natural earth tone, tropical resort style',
      },
      {
        id: 'sheer-trop',
        name: 'เฉพาะผ้าโปร่ง (Sheer Only)',
        description: 'พริ้วไหว รับลม เหมือนอยู่ริมทะเล',
        promptModifier: 'Sheer curtains only, breezy linen fabric, tropical resort interior',
      },
      {
        id: 's-curve-trop',
        name: 'ม่านลอน (S-Curve)',
        description: 'ผ้าฝ้ายหรือลินิน สีเอิร์ธโทน',
        promptModifier: 'S-Curve curtains, natural cotton or linen fabric, earth tones, tropical style',
      },
      {
        id: 'pleated-trop',
        name: 'ม่านจีบ (Pleated)',
        description: 'เรียบง่าย ดูเป็นธรรมชาติ',
        promptModifier: 'Loose pleated curtains, natural texture, tropical home decor',
      },
      {
        id: 'eyelet-trop',
        name: 'ม่านตาไก่ (Eyelet)',
        description: 'พริ้วไหวเป็นธรรมชาติ ระบายอากาศได้ดี',
        promptModifier: 'Tropical eyelet curtains, wooden rod, natural cotton texture, airy resort style',
      },
      {
        id: 'roman-trop',
        name: 'ม่านพับ (Roman)',
        description: 'ม่านพับไม้ไผ่ หรือผ้าลายธรรมชาติ',
        promptModifier: 'Woven wood Roman shades, bamboo blinds texture, tropical style',
      },
    ],
  },
  {
    id: 'contemporary',
    name: 'Contemporary',
    icon: '🛋️',
    description: 'ร่วมสมัย อบอุ่น อยู่สบาย ไม่ตกยุค',
    colors: 'bg-amber-50 text-amber-900 border-amber-200',
    curtains: [
      {
        id: 'pleated-cont',
        name: 'ม่านจีบ (Pleated)',
        description: 'เข้าได้กับทุกยุคสมัย อบอุ่น',
        promptModifier: 'Classic pleated curtains, warm contemporary style',
      },
      {
        id: 'eyelet-cont',
        name: 'ม่านตาไก่ (Eyelet)',
        description: 'ร่วมสมัย ใช้งานง่าย ลอนทิ้งตัวสวย',
        promptModifier: 'Contemporary eyelet curtains, clean waves, modern home decor',
      },
      {
        id: 'roller-cont',
        name: 'ม่านม้วน (Roller Blinds)',
        description: 'ดูแลรักษาง่าย ดูสะอาดตา',
        promptModifier: 'Contemporary roller shades, clean fabric window covering, modern home',
      },
      {
        id: 'sheer-cont',
        name: 'เฉพาะผ้าโปร่ง (Sheer Only)',
        description: 'โปร่งสบาย ให้ความรู้สึกผ่อนคลาย',
        promptModifier: 'Sheer curtains only, soft see-through fabric, contemporary living room',
      },
      {
        id: 'roman-cont',
        name: 'ม่านพับ (Roman)',
        description: 'ดูเป็นระเบียบ เหมาะกับหน้าต่างบานเล็ก',
        promptModifier: 'Fabric Roman blinds, soft folds, neat appearance, contemporary home decor',
      },
      {
        id: 's-curve-cont',
        name: 'ม่านลอน (S-Curve)',
        description: 'ทันสมัย ผสมผสานความนุ่มนวล',
        promptModifier: 'S-Curve curtains, wave drapery, cozy contemporary living room',
      },
      {
        id: 'wooden-cont',
        name: 'มู่ลี่ไม้ (Wooden Blinds)',
        description: 'ไม้สีธรรมชาติ เข้ากับบ้านสมัยใหม่',
        promptModifier: 'Wooden venetian blinds, natural wood color, contemporary style',
      },
      {
        id: 'vertical-cont',
        name: 'ม่านปรับแสง (Vertical Blinds)',
        description: 'ดูแลรักษาง่าย เหมาะกับห้องทำงาน',
        promptModifier: 'Vertical blinds, clean fabric slats, contemporary interior',
      },
    ],
  },
  {
    id: 'mid-century',
    name: 'Mid-Century Modern',
    icon: '📺',
    description: 'ย้อนยุค 50s-60s รูปทรงเรขาคณิต ไม้สีเข้ม',
    colors: 'bg-orange-50 text-orange-900 border-orange-200',
    curtains: [
      {
        id: 'wooden-mcm',
        name: 'มู่ลี่ไม้ (Wooden Blinds)',
        description: 'ไม้สีสัก (Teak) เอกลักษณ์ของยุคนี้',
        promptModifier: 'Teak wooden venetian blinds, mid-century modern style, retro 50s furniture',
      },
      {
        id: 's-curve-mcm',
        name: 'ม่านลอน (S-Curve)',
        description: 'สีสันสดใส หรือลวดลายเรขาคณิต',
        promptModifier: 'S-Curve curtains, bold color or geometric pattern, mid-century modern interior',
      },
      {
        id: 'roller-mcm',
        name: 'ม่านม้วน (Roller Blinds)',
        description: 'เรียบง่าย เน้นฟังก์ชัน',
        promptModifier: 'Simple roller shades, plain fabric, mid-century modern style',
      },
      {
        id: 'pleated-mcm',
        name: 'ม่านจีบ (Pleated)',
        description: 'คลาสสิก เรียบง่าย เข้ากับเฟอร์นิเจอร์ลอยตัว',
        promptModifier: 'Vintage pleated curtains, texture fabric, mid-century modern home',
      },
      {
        id: 'eyelet-mcm',
        name: 'ม่านตาไก่ (Eyelet)',
        description: 'เข้ากับรางม่านไม้หรือโลหะยุค 50s',
        promptModifier: 'Mid-century modern eyelet curtains, retro texture, metal or wood rod',
      },
      {
        id: 'roman-mcm',
        name: 'ม่านพับ (Roman)',
        description: 'เรียบเท่ เข้ากับหน้าต่างทรงสูง',
        promptModifier: 'Roman blinds, clean lines, retro modern style',
      },
      {
        id: 'vertical-mcm',
        name: 'ม่านปรับแสง (Vertical Blinds)',
        description: 'ได้รับความนิยมในยุค 60s',
        promptModifier: 'Vertical blinds, vintage aesthetic, mid-century modern office',
      },
      {
        id: 'sheer-mcm',
        name: 'เฉพาะผ้าโปร่ง (Sheer Only)',
        description: 'โปร่งโล่ง รับแสง เข้ากับกระจกบานใหญ่',
        promptModifier: 'Sheer curtains only, floor to ceiling windows, mid-century modern style',
      },
    ],
  },
];
